// react-appwrite/src/pages/Home.tsx
import React from "react";

const Home: React.FC = () => {
  const profile = {
    name: "Luu Cao Hoang",
    avatarUrl: "https://avatars.githubusercontent.com/u/136492579?v=4",
    role: "Software Engineer | Backend Developer | Spring Boot Enthusiastic",
    socialLinks: [
      {
        type: "github",
        url: "https://github.com/lcaohoanq",
        iconUrl: "/github.png",
      },
      {
        type: "gitlab",
        url: "https://gitlab.com/lcaohoanq",
        iconUrl: "/gitlab.png",
      },
      {
        type: "linkedin",
        url: "https://www.linkedin.com/in/lcaohoanq",
        iconUrl: "/linkedin.png",
      },
      {
        type: "ig",
        url: "https://instagram.com/lcaohoanq",
        iconUrl: "/ig.png",
      },
      {
        type: "unsplash",
        url: "https://unsplash.com/@lcaohoanq",
        iconUrl: "/unsplash.png",
      },
    ],
  };

  const handleNavigate = (url: string) => {
    window.open(url, "_blank");
  };

  return (
    <main className="flex flex-col md:flex-row items-center justify-center p-8 min-h-screen bg-[#f1f1f1] text-[#333]">
      <img
        className="avatar w-52 h-52 rounded-full object-cover mb-4 md:mb-0 md:mr-8"
        src={profile.avatarUrl}
        alt="Avatar"
      />
      <div className="content max-w-xl space-y-4">
        <h1 className="text-3xl font-semibold">{profile.name}</h1>
        <p className="text-lg text-gray-600">{profile.role}</p>
        <p>
          When I'm not coding, you'll likely find me capturing moments through
          my lens,{" "}
          <a
            href="https://unsplash.com/@lcaohoanq"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 underline"
          >
            Unsplash
          </a>
          , 📸 or enjoying a peaceful bike ride.
        </p>
        <p>
          I also enjoy sharing knowledge through my blog,{" "}
          <a
            href="https://shinbun.vercel.app/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 underline"
          >
            shinbun 新聞
          </a>
          , where I write about tech, development tips, and more.
        </p>

        {/* Portfolio Button */}
        <div className="pt-4">
          <a
            href="/portfolio"
            className="inline-block bg-blue-600 text-white px-8 py-3 rounded-lg hover:bg-blue-700 transition-colors font-medium"
          >
            View Full Portfolio →
          </a>
        </div>

        <div className="link-icons-container flex flex-wrap gap-4 mt-4">
          {profile.socialLinks.map((link) => (
            <div
              key={link.type}
              className="link-icon w-12 h-12 rounded-full flex items-center justify-center bg-white shadow hover:scale-110 transition-transform cursor-pointer"
              onClick={() => handleNavigate(link.url)}
            >
              <img
                src={link.iconUrl}
                alt={link.type}
                className="w-6 h-6 object-contain"
              />
            </div>
          ))}
        </div>
      </div>
    </main>
  );
};

export default Home;

// angular/pflio/src/app/home/home.component.ts
import { Component } from "@angular/core";

interface SocialLink {
  name: string;
  url: string;
}

@Component({
  selector: "app-home",
  templateUrl: "./home.component.html",
  styleUrls: ["./home.component.scss"],
})
export class HomeComponent {
  informationURL: SocialLink[] = [
    {
      name: "github",
      url: "https://github.com/lcaohoanq",
    },
    {
      name: "ig",
      url: "https://www.instagram.com/lcaohoanq/",
    },
  ];

  // Convert the array to a map
  informationURLMap: { [key: string]: string } = this.informationURL.reduce<{
    [key: string]: string;
  }>((acc, item) => {
    acc[item.name] = item.url;
    return acc;
  }, {});

  handleNavigate(name: string): void {
    const url = this.informationURLMap[name];

    if (url) {
      window.open(url, "_blank");
    }
  }
}

<div class="flex justify-center items-center gap-6 bg-[#f1f1f1] min-h-[100vh]">
  <img
    class="h-[20rem] w-[20rem] rounded-full"
    src="/assets/avatar.jpeg"
    alt="Avatar"
  />
  <div class="flex flex-col gap-4">
    <h1 class="text-2xl">Luu Cao Hoang</h1>
    <p class="text-[#606060]">GitHub account is lcaohoanq</p>
    <p class="text-[#606060]">Fullstack Web Developer</p>
    <div class="flex gap-2">
      <div
        (click)="handleNavigate('github')"
        class="link-icon flex justify-center items-center w-12 h-12 rounded-full bg-transparent transition-transform duration-300 hover:cursor-pointer hover:bg-[#d8d8d8] hover:scale-110"
      >
        <img class="w-12 h-12" src="/assets/github.png" alt="Github" />
      </div>
      <div
        (click)="handleNavigate('ig')"
        class="link-icon flex justify-center items-center w-12 h-12 rounded-full bg-transparent transition-transform duration-300 hover:cursor-pointer hover:bg-[#d8d8d8] hover:scale-110"
      >
        <img class="w-12 h-12" src="/assets/ig.png" alt="Instagram" />
      </div>
    </div>
  </div>
</div>
